version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build-be:
    docker:
      - image: "cimg/node:18.0"
    steps:
      - node/install:
          node-version: '18.0'
      - checkout
      - run:
          name: Install API Dependencies
          command: |
            echo "TODO: Install dependencies in the the backend API  "
            npm run api:install
      - run:
          name: API Build
          command: |
            echo "TODO: Build the backend API"
            npm run api:build
  build-fe:
    docker:
      - image: "cimg/node:16.0"
    steps:
      - node/install:
          node-version: '16.0'
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Front-End Lint
          command: |
            echo "TODO: Lint the frontend"
            npm run frontend:lint
      - run:
          name: Front-End Build
          command: |
            echo "TODO: Build the frontend app"
            npm run frontend:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.0'
      - checkout
      - eb/setup
      - run:
          name: Set ENV Elastic Beanstalk
          command: |
            eb init -p node.js -r $AWS_DEFAULT_REGION -k $AWS_ACCESS_KEY_ID --no-verify-ssl
            eb use $EB_ENV
            eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_HOST=$POSTGRES_HOST POSTGRES_DB=$POSTGRES_DB AWS_BUCKET=$AWS_BUCKET AWS_REGION=$AWS_REGION AWS_PROFILE=$AWS_PROFILE AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY JWT_SECRET=$JWT_SECRET
      - aws-cli/setup
      - run:
          name: Deploy App
          command: |
            echo "# TODO: Install, build, deploy in both apps"
            npm run deploy

workflows:
  udagram:
    jobs:
      - build-fe
      - build-be
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build-be
            - build-fe
      - deploy:
          requires:
            - hold